-- MySQL Script generated by MySQL Workbench
-- Wed Dec 16 14:35:38 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema AlphaSolutions
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `AlphaSolutions` ;

-- -----------------------------------------------------
-- Schema AlphaSolutions
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `AlphaSolutions` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `AlphaSolutions` ;

-- -----------------------------------------------------
-- Table `AlphaSolutions`.`Employees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AlphaSolutions`.`Employees` ;

CREATE TABLE IF NOT EXISTS `AlphaSolutions`.`Employees` (
  `Employee_Id` INT NOT NULL AUTO_INCREMENT,
  `First_Name` VARCHAR(50) NOT NULL,
  `Last_Name` VARCHAR(100) NOT NULL,
  `Profile_Picture` VARCHAR(200) NULL DEFAULT NULL,
  `Employee_Number` INT NOT NULL,
  `WorkHoursAvailable` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`Employee_Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `Employee_Id_UNIQUE` ON `AlphaSolutions`.`Employees` (`Employee_Id` ASC);

CREATE UNIQUE INDEX `Employee_Number_UNIQUE` ON `AlphaSolutions`.`Employees` (`Employee_Number` ASC);


-- -----------------------------------------------------
-- Table `AlphaSolutions`.`Skills`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AlphaSolutions`.`Skills` ;

CREATE TABLE IF NOT EXISTS `AlphaSolutions`.`Skills` (
  `Skill_Id` INT NOT NULL AUTO_INCREMENT,
  `Skill_Description` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`Skill_Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `Skill_Id_UNIQUE` ON `AlphaSolutions`.`Skills` (`Skill_Id` ASC);

CREATE INDEX `_idx` ON `AlphaSolutions`.`Skills` (`Skill_Id` ASC);


-- -----------------------------------------------------
-- Table `AlphaSolutions`.`EmployeeSkills`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AlphaSolutions`.`EmployeeSkills` ;

CREATE TABLE IF NOT EXISTS `AlphaSolutions`.`EmployeeSkills` (
  `Employee_Id` INT NOT NULL,
  `Skill_Id` INT NOT NULL,
  PRIMARY KEY (`Employee_Id`, `Skill_Id`),
  CONSTRAINT `Employee_Id`
    FOREIGN KEY (`Employee_Id`)
    REFERENCES `AlphaSolutions`.`Employees` (`Employee_Id`),
  CONSTRAINT `Skill_Id`
    FOREIGN KEY (`Skill_Id`)
    REFERENCES `AlphaSolutions`.`Skills` (`Skill_Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `Skill_Id_idx` ON `AlphaSolutions`.`EmployeeSkills` (`Skill_Id` ASC);


-- -----------------------------------------------------
-- Table `AlphaSolutions`.`Projects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AlphaSolutions`.`Projects` ;

CREATE TABLE IF NOT EXISTS `AlphaSolutions`.`Projects` (
  `Project_Id` INT NOT NULL AUTO_INCREMENT,
  `Project_Name` VARCHAR(100) NOT NULL,
  `Project_Description` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`Project_Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `Project_Id_UNIQUE` ON `AlphaSolutions`.`Projects` (`Project_Id` ASC);


-- -----------------------------------------------------
-- Table `AlphaSolutions`.`SubProjects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AlphaSolutions`.`SubProjects` ;

CREATE TABLE IF NOT EXISTS `AlphaSolutions`.`SubProjects` (
  `SubProject_Id` INT NOT NULL AUTO_INCREMENT,
  `Project_Id` INT NOT NULL,
  `SubProject_Name` VARCHAR(100) NOT NULL,
  `SubProject_Description` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`SubProject_Id`),
  CONSTRAINT `Project_Id_SP`
    FOREIGN KEY (`Project_Id`)
    REFERENCES `AlphaSolutions`.`Projects` (`Project_Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 36
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `SubProject_Id_UNIQUE` ON `AlphaSolutions`.`SubProjects` (`SubProject_Id` ASC);

CREATE INDEX `Project_Id_idx` ON `AlphaSolutions`.`SubProjects` (`Project_Id` ASC);


-- -----------------------------------------------------
-- Table `AlphaSolutions`.`SubProjectDependencies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AlphaSolutions`.`SubProjectDependencies` ;

CREATE TABLE IF NOT EXISTS `AlphaSolutions`.`SubProjectDependencies` (
  `SubProjectDependency_Id` INT NOT NULL,
  `SubProject_Id` INT NOT NULL,
  PRIMARY KEY (`SubProjectDependency_Id`, `SubProject_Id`),
  CONSTRAINT `subProject_Id_SPD`
    FOREIGN KEY (`SubProject_Id`)
    REFERENCES `AlphaSolutions`.`SubProjects` (`SubProject_Id`)
    ON DELETE CASCADE,
  CONSTRAINT `subProjectDependency_Id_SPD`
    FOREIGN KEY (`SubProjectDependency_Id`)
    REFERENCES `AlphaSolutions`.`SubProjects` (`SubProject_Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `subProject_Id_SPD_idx` ON `AlphaSolutions`.`SubProjectDependencies` (`SubProject_Id` ASC);


-- -----------------------------------------------------
-- Table `AlphaSolutions`.`SubProjectsEstimatetWorkHours`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AlphaSolutions`.`SubProjectsEstimatetWorkHours` ;

CREATE TABLE IF NOT EXISTS `AlphaSolutions`.`SubProjectsEstimatetWorkHours` (
  `SubProjectEWH_Id` INT NOT NULL AUTO_INCREMENT,
  `SubProject_Id` INT NOT NULL,
  `EstimatetWorkHours` DOUBLE NOT NULL,
  PRIMARY KEY (`SubProjectEWH_Id`),
  CONSTRAINT `SubProject_Id`
    FOREIGN KEY (`SubProject_Id`)
    REFERENCES `AlphaSolutions`.`SubProjects` (`SubProject_Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `SubProjectEWH_Id_UNIQUE` ON `AlphaSolutions`.`SubProjectsEstimatetWorkHours` (`SubProjectEWH_Id` ASC);

CREATE INDEX `SubProject_Id` ON `AlphaSolutions`.`SubProjectsEstimatetWorkHours` (`SubProject_Id` ASC);


-- -----------------------------------------------------
-- Table `AlphaSolutions`.`Tasks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AlphaSolutions`.`Tasks` ;

CREATE TABLE IF NOT EXISTS `AlphaSolutions`.`Tasks` (
  `Task_Id` INT NOT NULL AUTO_INCREMENT,
  `Project_Id` INT NOT NULL,
  `SubProject_Id` INT NOT NULL,
  `Task_Name` VARCHAR(50) NULL DEFAULT NULL,
  `Task_Description` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`Task_Id`),
  CONSTRAINT `Project_Id_Tasks`
    FOREIGN KEY (`Project_Id`)
    REFERENCES `AlphaSolutions`.`Projects` (`Project_Id`)
    ON DELETE CASCADE,
  CONSTRAINT `SubProject_Id_Tasks`
    FOREIGN KEY (`SubProject_Id`)
    REFERENCES `AlphaSolutions`.`SubProjects` (`SubProject_Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 31
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `Task_Id_UNIQUE` ON `AlphaSolutions`.`Tasks` (`Task_Id` ASC);

CREATE INDEX `SubProject_Id_idx` ON `AlphaSolutions`.`Tasks` (`SubProject_Id` ASC);

CREATE INDEX `Project_Id_Tasks_idx` ON `AlphaSolutions`.`Tasks` (`Project_Id` ASC);


-- -----------------------------------------------------
-- Table `AlphaSolutions`.`SubTasks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AlphaSolutions`.`SubTasks` ;

CREATE TABLE IF NOT EXISTS `AlphaSolutions`.`SubTasks` (
  `SubTask_Id` INT NOT NULL AUTO_INCREMENT,
  `Task_Id` INT NOT NULL,
  `SubTask_Description` VARCHAR(500) NULL DEFAULT NULL,
  `Project_Id` INT NOT NULL,
  `SubTask_Name` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`SubTask_Id`),
  CONSTRAINT `Project_Id_ST`
    FOREIGN KEY (`Project_Id`)
    REFERENCES `AlphaSolutions`.`Projects` (`Project_Id`)
    ON DELETE CASCADE,
  CONSTRAINT `Task_Id_ST`
    FOREIGN KEY (`Task_Id`)
    REFERENCES `AlphaSolutions`.`Tasks` (`Task_Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `SubTask_Id_UNIQUE` ON `AlphaSolutions`.`SubTasks` (`SubTask_Id` ASC);

CREATE INDEX `Task_Id_idx` ON `AlphaSolutions`.`SubTasks` (`Task_Id` ASC);

CREATE INDEX `Project_Id_ST_idx` ON `AlphaSolutions`.`SubTasks` (`Project_Id` ASC);


-- -----------------------------------------------------
-- Table `AlphaSolutions`.`SubTaskDependencies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AlphaSolutions`.`SubTaskDependencies` ;

CREATE TABLE IF NOT EXISTS `AlphaSolutions`.`SubTaskDependencies` (
  `subtaskdependency_Id` INT NOT NULL,
  `subtask_Id` INT NOT NULL,
  PRIMARY KEY (`subtaskdependency_Id`, `subtask_Id`),
  CONSTRAINT `subTask_Id_STD`
    FOREIGN KEY (`subtask_Id`)
    REFERENCES `AlphaSolutions`.`SubTasks` (`SubTask_Id`)
    ON DELETE CASCADE,
  CONSTRAINT `subTaskDependency_Id_STD`
    FOREIGN KEY (`subtaskdependency_Id`)
    REFERENCES `AlphaSolutions`.`SubTasks` (`SubTask_Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `subTask_Id_STD_idx` ON `AlphaSolutions`.`SubTaskDependencies` (`subtask_Id` ASC);


-- -----------------------------------------------------
-- Table `AlphaSolutions`.`SubTaskEstimatetWorkHours`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AlphaSolutions`.`SubTaskEstimatetWorkHours` ;

CREATE TABLE IF NOT EXISTS `AlphaSolutions`.`SubTaskEstimatetWorkHours` (
  `SubTaskEWH_Id` INT NOT NULL AUTO_INCREMENT,
  `Subtask_Id` INT NOT NULL,
  `EstimatetWorkHours` DOUBLE NOT NULL,
  PRIMARY KEY (`SubTaskEWH_Id`),
  CONSTRAINT `SubTask_Id`
    FOREIGN KEY (`Subtask_Id`)
    REFERENCES `AlphaSolutions`.`SubTasks` (`SubTask_Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `SubTaskEWH_Id_UNIQUE` ON `AlphaSolutions`.`SubTaskEstimatetWorkHours` (`SubTaskEWH_Id` ASC);

CREATE INDEX `SubTask_Id_idx` ON `AlphaSolutions`.`SubTaskEstimatetWorkHours` (`Subtask_Id` ASC);


-- -----------------------------------------------------
-- Table `AlphaSolutions`.`TaskDependencies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AlphaSolutions`.`TaskDependencies` ;

CREATE TABLE IF NOT EXISTS `AlphaSolutions`.`TaskDependencies` (
  `Task_Id` INT NOT NULL,
  `TaskDependency_Id` INT NOT NULL,
  PRIMARY KEY (`Task_Id`, `TaskDependency_Id`),
  CONSTRAINT `Task_Dependency_Id_TD`
    FOREIGN KEY (`TaskDependency_Id`)
    REFERENCES `AlphaSolutions`.`Tasks` (`Task_Id`)
    ON DELETE CASCADE,
  CONSTRAINT `Task_Id_TD`
    FOREIGN KEY (`Task_Id`)
    REFERENCES `AlphaSolutions`.`Tasks` (`Task_Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `Task_Dependency_Id_idx` ON `AlphaSolutions`.`TaskDependencies` (`TaskDependency_Id` ASC);


-- -----------------------------------------------------
-- Table `AlphaSolutions`.`TasksEstimatetWorkHours`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AlphaSolutions`.`TasksEstimatetWorkHours` ;

CREATE TABLE IF NOT EXISTS `AlphaSolutions`.`TasksEstimatetWorkHours` (
  `TasksEWH_Id` INT NOT NULL AUTO_INCREMENT,
  `Task_Id` INT NOT NULL,
  `EstimatetWorkHours` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`TasksEWH_Id`),
  CONSTRAINT `Task_Id`
    FOREIGN KEY (`Task_Id`)
    REFERENCES `AlphaSolutions`.`Tasks` (`Task_Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `Task_Id_UNIQUE` ON `AlphaSolutions`.`TasksEstimatetWorkHours` (`Task_Id` ASC);

CREATE UNIQUE INDEX `TasksEWH_Id_UNIQUE` ON `AlphaSolutions`.`TasksEstimatetWorkHours` (`TasksEWH_Id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
